### ISSUE TITLE
[Bug Report]: The stone cache is not installed

### ISSUE THREAD

**Issue by Sxwbns** [Deaadman/UniversalTweaks#11]
### The Long Dark Version

v2.35

### Mod Version

v1.4.3

### Describe the Issue

When trying to install a stone cache, nothing happens and "During invoking native - > managed trampoline" is output to the log

### Steps to Reproduce

Not required

### Log Output

[Latest.log](https://github.com/user-attachments/files/18093949/Latest.log)

**Comment by Deaadman** [comment]
Thank you for the report, I have been notified by others in the discord server. I'll get around to fixing this when I can, and then close this bug report.

**Comment by Deaadman** [comment]
This issue should have been fixed in the latest release - [v1.4.4](https://github.com/Deaadman/UniversalTweaks/releases/tag/v1.4.4).

Thank you for the bug report!
